### ISSUE TITLE
 "Space spacing" issue

### ISSUE THREAD

**Issue by HgonKim** [tunerok/unity_browser#2]
First Thank you for your "unity browser engine".

I build a Window program with this package in Unity. 
When the program's path has a ' '(Space character), it doesn't start a plugin process... 
But if this program's path doesn't have a ' '(Space character), it start a plugin process and do very well!!

How can I fix it for program which has a ' '(Space character)??

Thanks

**Comment by NanjiaW** [comment]
Hi Kim,

If your problem solved? I have been trying to build this but keep getting error saying that mssing SharedMemeory namespace. Have you encountered the same issue?

**Comment by tunerok** [comment]
@HgonKim have you got any logs?

**Comment by tunerok** [comment]
@NanjiaW do you used test project or really compiled plugin?

**Comment by NanjiaW** [comment]
@tunerok Thanks for reply! Unity is new to me but here's what I've tried:
1. I download the unity package from vitaly_chashin, it runs fine in unity but when I tried to build it for UWP, it failed and showing that missing SharedMemory namespace.
2. After fail to fix the bug by myself, I look up only see if someone had fixed that issue, and I found ur GitHub repository and the one done by Dmitry.
3. In your repository  the web_browser has already been built into Solution, so I am wondering if you could share the unity package file?
4. Since there's no unity package file, I import the project using UnityClient folder, but got lot's of bugs.
Thank you very much for taking your time reading this. Really appreciate if you can provide some suggestion.

**Comment by HgonKim** [comment]
Oh..!
I'd solved this problem!!! 
But I have one more question..
ㄴ>sometimes the plugin has no response. But after restarting the program, then plugin does well..!
Can I fix i??

**Comment by tunerok** [comment]
@HgonKim hi
Can you share solution with us, please?)

**Comment by HgonKim** [comment]
I want to know your accurate problem.
Can you send me your log or something??

Thanks

--------------------------------------------------------------

김현곤 (khg@robotis.com)
스팀 팀 / 주임 연구원

㈜로보티즈 (http://www.robotis.com)

07594 서울시 강서구 마곡중앙5로 1길 37 로보티즈캠퍼스
Tel : +82-70-8671-2908, Fax : +82-70-8230-1336



<http://www.robotis.com/>


2020년 6월 29일 (월) 오전 12:20, Artem <notifications@github.com>님이 작성:

**Comment by iletai** [comment]
> @HgonKim hi
> Can you share solution with us, please?)

Issues come from Input.GetKey return a null value when sending char. And enum defines of Unity different. You can see more fore [here](https://docs.unity3d.com/ScriptReference/Input-inputString.html). So to detect it, let handle for special keypress as (dot, backspace..) by sample code:
```
 foreach (KeyCode k in Enum.GetValues(typeof(KeyCode)))
 {
    if (Input.GetKey(code))
    {            if (code == KeyCode.Backspace) // || KeyCode.KeyNeedHandle
                {
                    mainEngine.SendCharEvent((int)code, KeyEvents.Down);
                }
   }
}
```

**Comment by HgonKim** [comment]
Hi. sorry to be late.
you mean the Unity can't return a value for "backspace"??

**Comment by iletai** [comment]
> Hi. sorry to be late.
> 
> you mean the Unity can't return a value for "backspace"?? 
> 
> 
> 
> 

You can try wirte log for see value return.
